# Generated by Django 5.2.3 on 2026-03-22 12:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Уникальный ключ, например: company_description, agronomist_persona', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Название для отображения в админке', max_length=255)),
                ('content', models.TextField(help_text='Текст контекста, который будет добавлен в промпт ИИ')),
                ('is_active', models.BooleanField(default=True, help_text='Включён ли этот контекст')),
                ('priority', models.IntegerField(default=0, help_text='Порядок в системном промпте (меньше = выше)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Контекст',
                'verbose_name_plural': 'AI Контексты',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, help_text='Тип источника: news, project, company_info, partner, certificate, contact_info', max_length=50)),
                ('source_id', models.IntegerField(help_text='ID записи в исходной таблице')),
                ('language', models.CharField(default='ru', max_length=5)),
                ('content_text', models.TextField()),
                ('content_title', models.CharField(blank=True, max_length=500)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Эмбеддинг документа',
                'verbose_name_plural': 'Эмбеддинги документов',
                'unique_together': {('source_type', 'source_id', 'language')},
            },
        ),
    ]
